server:
  port: 8001

spring:
  application:
    name: plasma-provider-payment-8001
  profiles:
#    自由切换开发环境、生产环境
    active: dev
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.haozai.plasma.entity
#它一般对应我们的实体类所在的包，这个时候会自动取对应包中不包括包名的简单类名作为包括包名的别名。多个package之间可以用逗号或者分号等来进行分隔（value的值一定要是包的全）
